services:
  - type: web
    name: noteapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn noteapp.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: noteapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: noteapp-db
    databaseName: noteapp
    user: noteapp
    plan: starter